### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by hblaschka** [pascalmattes/homee-terminal#1]
Hi Pascal,

does this need to be installed locally ATM (if so, how?) as the package seems not to be available on the registry?

`yarn add homee-terminal`
leads to
> An unexpected error occurred: "https://registry.yarnpkg.com/homee-terminal: Not found".

**Comment by pascalmattes** [comment]
Hi @hblaschka,

this is a web application and therefore it has to be hosted either locally or on a web server.

At the moment there are two options: 
- **Run it locally**
You can pull the repository, install the dependencies with `yarn install` and run it with `yarn dev`. Afterwards you can access the terminal at `http://localhost:3000/homee-terminal/`

- **Use my hosted version**
This isn't guaranteed to be accessible but you can find it at `https://pascalmattes.de/homee-terminal/`

**Comment by hblaschka** [comment]
Thanks, Pascal!

Is there any idea or plan to provide access to the terminal in the context of any of the hom.ee domains (e.g. terminal.hom.ee or my.hom.ee/terminal)? This would make it possible to recommend the usage of the terminal to newbies that either would not be able to install themselves or that would not want to access a hosted version outside of the control of CA/homee GmbH...

**Comment by pascalmattes** [comment]
This is a private project and not related to homee or Codeatelier. Therefore it will not be available at a homee subdomain.

**Comment by hblaschka** [comment]
OK, thanks for the info.
